name: Build and deploy sample web app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Check Resource Group Existence
        id: check-rg
        run: |
          EXISTS=$(az group exists --name "testRG")
          echo "RG_EXISTS=$EXISTS" >> $GITHUB_ENV

      - name: Delete Resource Group if Exists
        if: env.RG_EXISTS == 'true'
        run: |
          az group delete --name "testRG" --yes

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  
  deploy:
    runs-on: ubuntu-latest
    needs: setup-infrastructure
    environment:
      name: "Production"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Retrieve Azure Web App Publish Profile
        id: getpublishprofile
        run: |
          PUBLISH_PROFILE=$(az webapp deployment list-publishing-profiles --name "tweet-text-splitter" --resource-group "testRG" --xml)
          echo "PUBLISH_PROFILE<<EOF" >> $GITHUB_ENV
          echo "$PUBLISH_PROFILE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
  
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "web-app"
          slot-name: "Production"
          package: ./appserviceweb
          publish-profile: ${{ env.PUBLISH_PROFILE }}